version: '3.8'

services:
  api:
    image: ${DOCKER_USERNAME:-yourusername}/web3-summarizer-api:latest
    container_name: web3-summarizer-api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/web3_summarizer
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - WEB3_PROVIDER_URL=${WEB3_PROVIDER_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - web3-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  db:
    image: postgres:14
    container_name: web3-summarizer-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=web3_summarizer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web3-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  web3-network:
    driver: bridge

volumes:
  postgres_data:
