version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=sqlite:///./summarizer.db
      # Uncomment and set these in production
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      # - WEB3_PROVIDER_URL=${WEB3_PROVIDER_URL}
    restart: unless-stopped
